geolocalizacion/protectedx/models/Objetos.php
<?php

/**
 * This is the model class for table "objetos".
 *
 * The followings are the available columns in table 'objetos':
 * @property integer $idobjeto
 * @property string $nombre
 * @property string $descripcion
 * @property string $direccion
 * @property string $latitud
 * @property string $longitud
 * @property string $zoom
 * @property string $usuariocrea
 * @property string $creado
 * @property string $usuariomodifica
 * @property string $actualizado
 * @property string $ip
 * @property string $imagen1
 * @property string $imagen2
 * @property string $imagen3
 * @property boolean $status
 *
 * The followings are the available model relations:
 * @property Comentarios[] $comentarioses
 * @property Categoriaobjeto[] $categoriaobjetos
 * @property Objetoetiqueta[] $objetoetiquetas
 * @property Visitas[] $visitases
 * @property Atributoobjeto[] $atributoobjetos
 * @property Calificaciones[] $calificaciones
 */
class Objetos extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'objetos';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nombre, descripcion, direccion, latitud, longitud, zoom', 'required'),
			array('nombre, usuariocrea, usuariomodifica, ip', 'length', 'max'=>80),
			array('descripcion', 'length', 'max'=>300),
			array('direccion, latitud, longitud', 'length', 'max'=>40),
			// array('imagen1, imagen2, imagen3', 'length', 'max'=>30),
			array('imagen1, imagen2, imagen3', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'), 
			array('creado, actualizado, status', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idobjeto, nombre, descripcion, direccion, latitud, longitud, zoom, usuariocrea, creado, usuariomodifica, actualizado, ip, imagen1, imagen2, imagen3, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'comentarioses' => array(self::HAS_MANY, 'Comentarios', 'idobjeto'),
			'categoriaobjetos' => array(self::HAS_MANY, 'Categoriaobjeto', 'idobjeto'),
			'objetoetiquetas' => array(self::HAS_MANY, 'Objetoetiqueta', 'idobjeto'),
			'visitases' => array(self::HAS_MANY, 'Visitas', 'idobjeto'),
			'atributoobjetos' => array(self::HAS_MANY, 'Atributoobjeto', 'idobjeto'),
			'calificaciones' => array(self::HAS_MANY, 'Calificaciones', 'idobjeto'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idobjeto' => 'Idobjeto',
			'nombre' => 'Nombre',
			'descripcion' => 'Descripcion',
			'direccion' => 'Direccion',
			'latitud' => 'Latitud',
			'longitud' => 'Longitud',
			'zoom' => 'Zoom',
			'usuariocrea' => 'Usuariocrea',
			'creado' => 'Creado',
			'usuariomodifica' => 'Usuariomodifica',
			'actualizado' => 'Actualizado',
			'ip' => 'Ip',
			'imagen1' => 'Imagen1',
			'imagen2' => 'Imagen2',
			'imagen3' => 'Imagen3',
			'status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idobjeto',$this->idobjeto);
		$criteria->compare('nombre',$this->nombre,true);
		$criteria->compare('descripcion',$this->descripcion,true);
		$criteria->compare('direccion',$this->direccion,true);
		$criteria->compare('latitud',$this->latitud,true);
		$criteria->compare('longitud',$this->longitud,true);
		$criteria->compare('zoom',$this->zoom,true);
		$criteria->compare('usuariocrea',$this->usuariocrea,true);
		$criteria->compare('creado',$this->creado,true);
		$criteria->compare('usuariomodifica',$this->usuariomodifica,true);
		$criteria->compare('actualizado',$this->actualizado,true);
		$criteria->compare('ip',$this->ip,true);
		$criteria->compare('imagen1',$this->imagen1,true);
		$criteria->compare('imagen2',$this->imagen2,true);
		$criteria->compare('imagen3',$this->imagen3,true);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Objetos the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

geolocalizacion/protectedx/controllers/ObjetosController.php
<?php
Yii::import('ext.gmap.*');
class ObjetosController extends Controller
{
	

	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','desactivar'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('admin','create','update','delete'),
				'roles'=>array('admin'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','create','update','delete'),
				'roles'=>array('super'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','create','update','delete'),
				'users'=>array('jaco'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Objetos;
		if(isset($_POST['Objetos']))
		{
			$model->attributes=$_POST['Objetos'];
			$rnd1 = rand(0,9999);
			$rnd2 = rand(0,9999);
			$rnd3 = rand(0,9999); 
            $uploadedFile1=CUploadedFile::getInstance($model,'imagen1');
            $uploadedFile2=CUploadedFile::getInstance($model,'imagen2');
            $uploadedFile3=CUploadedFile::getInstance($model,'imagen3');
           	$fileName1 = "{$rnd1}-{$uploadedFile1}"; $fileName2 = "{$rnd2}-{$uploadedFile2}"; $fileName3 = "{$rnd3}-{$uploadedFile3}";
			if (empty($uploadedFile1)) {
 				$fileName1 = 'default.jpg'; 
			}
			if (empty($uploadedFile2)) {
 				$fileName2 = 'default.jpg'; 
			}
			if (empty($uploadedFile3)) {
 				$fileName3 = 'default.jpg'; 
			}
            $model->imagen1 = $fileName1;
            $model->imagen2 = $fileName2;
            $model->imagen3 = $fileName3;
        }
			if($model->save()) {
				if(!empty($uploadedFile1)) {
   					$uploadedFile1->saveAs(Yii::app()->basePath.'/../images/'.$fileName1);
				}
				if(!empty($uploadedFile2)) {
   					$uploadedFile2>saveAs(Yii::app()->basePath.'/../images/'.$fileName2);
				}
				if(!empty($uploadedFile)) {
   					$uploadedFile3->saveAs(Yii::app()->basePath.'/../images/'.$fileName3);
				}

				$this->redirect(array('view','id'=>$model->idobjeto));

			}
		

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
        $oldFileName1 = $model->imagen1;
        $oldFileName2 = $model->imagen2;
        $oldFileName3 = $model->imagen3;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Objetos']))
		{
			$model->attributes=$_POST['Objetos'];
			$uploadedFile1=CUploadedFile::getInstance($model,'imagen1');
			$uploadedFile2=CUploadedFile::getInstance($model,'imagen2');
			$uploadedFile3=CUploadedFile::getInstance($model,'imagen3');

			if ($uploadedFile1 !== null) {
				$model->imagen1 = $uploadedFile1;
			} else {
				$model->imagen1 = $oldFileName1;
			}
			if ($uploadedFile2 !== null) {
				$model->imagen2 = $uploadedFile2;
			} else {
				$model->imagen2 = $oldFileName2;
			}
			if ($uploadedFile3 !== null) {
				$model->imagen3 = $uploadedFile3;
			} else {
				$model->imagen3 = $oldFileName3;
			}



			if($model->save())
				  if(!empty($uploadedFile1)) { $uploadedFile1->saveAs(Yii::app()->basePath.'/../images/'.$model->imagen1); }
				  if(!empty($uploadedFile2)) { $uploadedFile2>saveAs(Yii::app()->basePath.'/../images/'.$model->imagen2); }
				  if(!empty($uploadedFile3)) { $uploadedFile3>saveAs(Yii::app()->basePath.'/../images/'.$model->imagen3); }				
				$this->redirect(array('view','id'=>$model->idobjeto));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}


	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
	
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{//urgente codigo tentativo para la consulta sql  ALTER TABLE public.objetos ADD COLUMN status boolean; ALTER TABLE public.objetos ALTER COLUMN status SET DEFAULT true;

// <?php echo CHtml::link(CHtml::encode($data->nombre), array('view', 'id'=>$data->idobjeto)); 


		$dataProvider=new CActiveDataProvider('Objetos');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Objetos('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Objetos']))
			$model->attributes=$_GET['Objetos'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Objetos the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Objetos::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


public function actionDesactivar($id)
	{
		$model=Objetos::model()->findByPk($_GET['id']);
		// var_dump(expression)
		if ($model->status == true) {
		$model->status = false;
		echo "ta";
			$model->save();

		}
		else {
			echo "nota";
			$model->status = true;
			$model->save();
		}
		$this->redirect(array('/objetos'));
		// if($model===null)
			// throw new CHttpException(404,'The requested page does not exist.');
		// return $model;
	}
	/**
	 * Performs the AJAX validation.
	 * @param Objetos $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='objetos-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
}

geolocalizacion/protectedx/views/objetos/_form.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */
/* @var $form CActiveForm */
?>

<div class="form">
	<div class="gllpLatlonPicker">
    <fieldset class="gllpLatlonPicker">
	<br/> <?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'objetos-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
	'enableClientValidation'=>true,
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
		),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>80)); ?>
		<?php echo $form->error($model,'nombre'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'descripcion'); ?>
		<?php echo $form->textField($model,'descripcion',array('size'=>60,'maxlength'=>300)); ?>
		<?php echo $form->error($model,'descripcion'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'direccion'); ?>
		<?php echo $form->textField($model,'direccion',array('size'=>40,'maxlength'=>40)); ?>
		<?php echo $form->error($model,'direccion'); ?>
	</div>


<?php if ($model->isNewRecord!='1'): ?>

	<div class="row">
     <?php echo CHtml::image(Yii::app()->request->baseUrl.'/images/'.$model->imagen1,"imagen",array("width"=>200)); ?>
	</div>
	<div class="row">
     <?php echo CHtml::image(Yii::app()->request->baseUrl.'/images/'.$model->imagen2,"imagen",array("width"=>200)); ?>
	</div>
	<div class="row">
     <?php echo CHtml::image(Yii::app()->request->baseUrl.'/images/'.$model->imagen2,"imagen",array("width"=>200)); ?>
	</div>
	<?php // else: ?>
	<?php endif ?>
		<div class="row">
			<?= $form->labelEx($model,'imagen1').CHtml::activeFileField($model, 'imagen1').$form->error($model,'imagen1'); ?>
		</div>
		<div class="row">
			<?= $form->labelEx($model,'imagen2').CHtml::activeFileField($model, 'imagen2').$form->error($model,'imagen2'); ?>
		</div>
		<div class="row">
			<?= $form->labelEx($model,'imagen3').CHtml::activeFileField($model, 'imagen3').$form->error($model,'imagen3'); ?>
		</div>
		

</div>
<input type="text" class="gllpSearchField" />

<input type="button" class="gllpSearchButton" value="search">

	<div class="gllpMap" id="map_canvas">
	</div>
		<?php echo $form->labelEx($model,'latitud'); ?>
		<?php echo $form->textField($model,'latitud',array('size'=>40,'maxlength'=>40, 'value'=> $model->latitud, 'class'=>'gllpLatitude')); ?>
		<?php echo $form->error($model,'latitud'); ?>
	</br>

		<?php echo $form->labelEx($model,'longitud'); ?>
		<?php echo $form->textField($model,'longitud',array('size'=>40,'maxlength'=>40,'value'=> $model->longitud, 'class'=>'gllpLongitude')); ?>
		<?php echo $form->error($model,'longitud'); ?>
</br>
		<?php echo $form->labelEx($model,'zoom'); ?>
		<?php echo $form->textField($model,'zoom',array('size'=>40,'maxlength'=>40,'value'=> $model->zoom, 'class'=>'gllpZoom')); ?>
		<?php echo $form->error($model,'zoom'); ?>


	<div class="row">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>


	

<?php $this->endWidget(); ?>
</fieldset>
  </div>

<script type="text/javascript">

function initialize() {
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var myOptions = {
        zoom: 7,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"),
            myOptions);
}
google.maps.event.addDomListener(window, "load", initialize);

</script>
</div><!-- form -->

geolocalizacion/protectedx/views/objetos/_search.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'idobjeto'); ?>
		<?php echo $form->textField($model,'idobjeto'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>80)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'descripcion'); ?>
		<?php echo $form->textField($model,'descripcion',array('size'=>60,'maxlength'=>300)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'direccion'); ?>
		<?php echo $form->textField($model,'direccion',array('size'=>40,'maxlength'=>40)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'latitud'); ?>
		<?php echo $form->textField($model,'latitud',array('size'=>40,'maxlength'=>40)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'longitud'); ?>
		<?php echo $form->textField($model,'longitud',array('size'=>40,'maxlength'=>40)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'zoom'); ?>
		<?php echo $form->textField($model,'zoom',array('size'=>40,'maxlength'=>40)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

geolocalizacion/protectedx/views/objetos/_view.php
<?php
/* @var $this ObjetosController */
/* @var $data Objetos */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idobjeto')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idobjeto), array('view', 'id'=>$data->idobjeto)); ?>
	<br />
	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php var_dump($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombre')); ?>:</b>
	<?php echo CHtml::encode($data->nombre); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('descripcion')); ?>:</b>
	<?php echo CHtml::encode($data->descripcion); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('direccion')); ?>:</b>
	<?php echo CHtml::encode($data->direccion); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('latitud')); ?>:</b>
	<?php echo CHtml::encode($data->latitud); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('longitud')); ?>:</b>
	<?php echo CHtml::encode($data->longitud); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('zoom')); ?>:</b>
	<?php echo CHtml::encode($data->zoom); ?>
	<br />

	
	
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('Categorias')); ?>:</b>
	<?php 
		$categoriaobjetos=Categorias::model()->findAllBySql('select categorias.nombre from categoriaobjeto INNER JOIN categorias on categoriaobjeto.idcategoria = categorias.idcategoria where categoriaobjeto.idobjeto ='.$data->idobjeto);
foreach ($categoriaobjetos as $key => $value) {
	echo $value['nombre'].'<br>';
}

	?>
	<br />


	<b><?php echo CHtml::encode($data->getAttributeLabel('Atributos')); ?>:</b>
	<?php 
		$atributoobjetos=Atributos::model()->findAllBySql('select atributos.nombre 
from atributoobjeto INNER JOIN atributos on atributoobjeto.idatributo = atributos.idatributo where atributoobjeto.idobjeto ='.$data->idobjeto);
foreach ($atributoobjetos as $key => $value) {
	echo $value['nombre'].'<br>';
}

	?>
	<br />


	<b><?php echo CHtml::encode($data->getAttributeLabel('Etiquetas')); ?>:</b>
	<?php 
		$objetoetiquetas=Etiquetas::model()->findAllBySql('select etiquetas.nombre 
from objetoetiqueta INNER JOIN etiquetas on objetoetiqueta.idetiqueta = etiquetas.idetiqueta where objetoetiqueta.idobjeto ='.$data->idobjeto);
foreach ($objetoetiquetas as $key => $value) {
	echo $value['nombre'].'<br>';
}

	?>
	<br />


	
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('visitases')); ?>:</b>
	<?php 
	foreach ($data->visitases as $exp){
		echo $exp->idvisitas.'<br>';
	}
	?>
	<br />


	
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('comentarioses')); ?>:</b>
	<?php 
	foreach ($data->comentarioses as $exp){
		echo $exp->comentario.'<br>';
	}
	?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('calificaciones')); ?>:</b>
	<?php 
	foreach ($data->calificaciones as $exp){
		echo $exp->calificacion.'<br>';
	}
	?>
	<br />
<?php

 echo CHtml::link('Desactivar objeto', array('objetos/desactivar', 'id'=>$data->idobjeto));
  	?>

</div>

geolocalizacion/protectedx/views/objetos/admin.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */

$this->breadcrumbs=array(
	'Objetoses'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Objetos', 'url'=>array('index')),
	array('label'=>'Create Objetos', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#objetos-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Objetoses</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'objetos-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'idobjeto',
		'nombre',
		'descripcion',
		'direccion',
		'latitud',
		'longitud',
		'zoom',


		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

geolocalizacion/protectedx/views/objetos/create.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */

$this->breadcrumbs=array(
	'Objetoses'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Objetos', 'url'=>array('index')),
	array('label'=>'Manage Objetos', 'url'=>array('admin')),
);
?>

<h1>Create Objetos</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

geolocalizacion/protectedx/views/objetos/index.php
<?php
/* @var $this ObjetosController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Objetoses',
);

$this->menu=array(
	array('label'=>'Create Objetos', 'url'=>array('create')),
	array('label'=>'Manage Objetos', 'url'=>array('admin')),
);
?>

<h1>Lista de Objetos</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

geolocalizacion/protectedx/views/objetos/update.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */

$this->breadcrumbs=array(
	'Objetoses'=>array('index'),
	$model->idobjeto=>array('view','id'=>$model->idobjeto),
	'Update',
);

$this->menu=array(
	array('label'=>'List Objetos', 'url'=>array('index')),
	array('label'=>'Create Objetos', 'url'=>array('create')),
	array('label'=>'View Objetos', 'url'=>array('view', 'id'=>$model->idobjeto)),
	array('label'=>'Manage Objetos', 'url'=>array('admin')),
);
?>

<h1>Update Objetos <?php echo $model->idobjeto; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

geolocalizacion/protectedx/views/objetos/view.php
<?php
/* @var $this ObjetosController */
/* @var $model Objetos */

$this->breadcrumbs=array(
	'Objetoses'=>array('index'),
	$model->idobjeto,
);

$this->menu=array(
	array('label'=>'List Objetos', 'url'=>array('index')),
	array('label'=>'Create Objetos', 'url'=>array('create')),
	array('label'=>'Update Objetos', 'url'=>array('update', 'id'=>$model->idobjeto)),
	array('label'=>'Delete Objetos', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->idobjeto),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Objetos', 'url'=>array('admin')),
);
?>

<h1>View Objetos #<?php echo $model->idobjeto; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'idobjeto',
		'nombre',
		'descripcion',
		'direccion',
		'latitud',
		'longitud',
		'zoom',

	),
)); ?>